backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

publish_mode: editorial_workflow # Allows you to save drafts before publishing them
media_folder: static/uploads # Where media files are stored
public_folder: /uploads # The src attribute for uploaded media will begin with this

site_url: https://shelfgeniecom.netlify.app

collections:
  - name: "posts"
    label: "Posts"
    label_singular: "Post"
    folder: "_posts/blog"
    create: true
    slug: "{{slug}}"
    preview_path: "blog/{{slug}}"
    fields:
      - label: "Featured Image"
        name: "thumbnail"
        widget: "image"
        required: false
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Body"
        name: "body"
        widget: "markdown"
